# Generated by Django 4.2.1 on 2023-05-18 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000000)),
                ('dated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
